<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Lupa de la caja de busqueda de wikipedia</name>
   <tag></tag>
   <elementGuidId>cd0e7072-477b-4eaf-8ab0-7b0363e25a5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#searchInput</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>450a47d3-e9e8-42de-b1e1-7e1fec926c38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vector-search-box-input</value>
      <webElementGuid>681b689c-ea30-46f6-849f-22a376f6dc49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>68648ad2-792e-47a9-9c1b-9ab92cf5152f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>2f4af136-8dca-486e-aef7-f36a90d735e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Buscar en Wikipedia</value>
      <webElementGuid>51497ca4-c47e-4998-996c-69bd9195f686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Buscar en Wikipedia</value>
      <webElementGuid>1f797f5b-29a1-46dd-8c67-5cc62105e8a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>sentences</value>
      <webElementGuid>7f6e1902-3aea-4ffd-89e6-9754e1643f83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Buscar en este wiki [ctrl-option-f]</value>
      <webElementGuid>ef6590c3-91e4-47a4-bc6a-0b9def9f6f34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accesskey</name>
      <type>Main</type>
      <value>f</value>
      <webElementGuid>ea399ea7-cff6-4311-a2d1-3a5925d66b07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchInput</value>
      <webElementGuid>9a2ccb5b-1591-471a-92cc-7be78d091dc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5425ef56-d83a-451e-8cc6-49f3141a3031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchInput&quot;)</value>
      <webElementGuid>33a70dc5-5529-44eb-be67-008e77b07418</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchButton']</value>
      <webElementGuid>8bda9966-5e63-4ce3-ae7b-532116173254</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
