<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Titulo de la pagina Teruel Existe</name>
   <tag></tag>
   <elementGuidId>c8a40e60-7750-4502-9e2c-f44051a887fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='firstHeading']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.mw-page-title-main</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>96667c58-690f-43d3-ada0-da7d1124595d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mw-page-title-main</value>
      <webElementGuid>deb5437d-e614-46e8-9a7a-8e6454ea6154</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Teruel Existe</value>
      <webElementGuid>a13f65b4-4c9b-42d9-b94d-8ab2f0cbbe2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;firstHeading&quot;)/span[@class=&quot;mw-page-title-main&quot;]</value>
      <webElementGuid>d62a1de6-ea0f-4703-ae59-b71057938f3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h1[@id='firstHeading']/span</value>
      <webElementGuid>12ce0330-82b1-4538-b046-ca33dd07d6bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='De Wikipedia, la enciclopedia libre'])[1]/preceding::span[1]</value>
      <webElementGuid>270d8948-9b3f-4afe-8f2c-6c0e8268334b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Teruel Existe']/parent::*</value>
      <webElementGuid>c53b3837-c0fd-47a2-9920-b18e7015dc4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>8f1abb26-0356-425e-90af-668d425f33d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Teruel Existe' or . = 'Teruel Existe')]</value>
      <webElementGuid>bc9d82c2-b9fd-48db-a210-7d40f52096d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
